services:
  web:
      build: .
      ports:
        - "3000:3000"
      environment:
        - DATABASE_URL=postgresql://postgres:pass@db:5432/websec
      depends_on:
        - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: websec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
volumes:
  postgres_data:
